kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - cd web
      - npm install
      - npm run build
      - cd ..
    when:
      branch:
        - master
      event:
        - push

  - name: deploy-testing
    image: debian
    commands:
      - tar -czf botamusique.tar.gz .
      - mv botamusique.tar.gz /tmp/botamusique/sources.tar.gz
    volumes:
      - name: repo
        path: /tmp/botamusique/
    when:
      branch:
        - master
      event:
        - push
  
  - name: docker
    image: plugins/docker
    settings:
      repo: azlux/botamusique
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: testing
    when:
      branch:
        - master
      event:
        - push

  - name: deploy-stable
    image: debian
    commands:
      - tar -czf botamusique.tar.gz .
      - mv botamusique.tar.gz /tmp/botamusique/sources.tar.gz
    volumes:
      - name: repo
        path: /tmp/botamusique/
    when:
      branch:
        - master
      event:
        - tag
        
   - name: docker
    image: plugins/docker
    settings:
      repo: azlux/botamusique
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
    when:
      branch:
        - master
      event:
        - tag


volumes:
- name: repo
  host:
    path: /media/raid5/data/packages/repos/apt/botamusique/
