kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
        - npm install
        - npm run build

  - name: deploy
    image: debian
    commands:
        - tar -czf botamusique.tar.gz .
        - mv botamusique.tar.gz /tmp/botamusique/sources-test.tar.gz
        
    volumes:
        - /media/raid5/data/packages/repos/apt/botamusique/:/tmp/botamusique/
