kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - cd web
      - npm install
      - npm run build
      - cd ..
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  - name: deploy-testing
    image: debian
    commands:
      - apt-get -qq update && apt-get -qq install git > /dev/null
      - sed -i 's/target_version = git/target_version = testing/' configuration.default.ini
      - version=$(git rev-parse HEAD)
      - echo "current git commit is $version"
      - echo $version > /tmp/botamusique/testing-version
      - sed -i "s/version = 'git'/version = '$version'/" mumbleBot.py
      - rm -rf .git*
      - rm -rf web
      - tar -czf /tmp/botamusique/sources-testing.tar.gz .
    volumes:
      - name: repo
        path: /tmp/botamusique/
    when:
      branch:
        - master
      event:
        - push
  
  - name: docker-testing
    image: plugins/docker
    settings:
      repo: azlux/botamusique
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: testing
    when:
      branch:
        - master
      event:
        - push


  - name: deploy-stable
    image: debian
    commands:
      - apt -qq update && apt -qq install jq curl git
      - rm -rf .git*
      - rm -rf web
      - sed -i 's/target_version = git/target_version = stable/' configuration.default.ini
      - git fetch --tags
      - version=$(git describe --abbrev=0 --tags)
      - echo "version is $version"
      - echo $version > /tmp/botamusique/version
      - sed -i "s/version = 'git'/version = '$version'/" mumbleBot.py
      - curl --silent "https://api.github.com/repos/azlux/botamusique/releases/latest" | jq -r '.body' > /tmp/botamusique/changelog
      - tar -czf /tmp/botamusique/sources-stable.tar.gz .
    volumes:
      - name: repo
        path: /tmp/botamusique/
    when:
      branch:
        - master
      event:
        - tag

  - name: docker-stable
    image: plugins/docker
    settings:
      repo: azlux/botamusique
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest
    when:
      branch:
        - master
      event:
        - tag

volumes:
- name: repo
  host:
    path: /media/raid5/data/packages/repos/apt/botamusique/
